# https://docs.codecov.com/docs/common-recipe-list
comment:
  require_changes: true

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "queng_cli"  # ignore folders and all its contents
  - "queng_components/db_manager"
  - "queng_components/file_manager"
  - "queng_components/svc_manager"
  - "queng_components/qd_manager"
  - "queng_proto"
  - "queng_providers"
  - "queng_sbe"
  - "queng_utils"
  - "queng_services"
