# https://docs.codecov.com/docs/common-recipe-list
comment:
  require_changes: true

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "cli"  # ignore folders and all its contents
  - "clients"
  - "components/db_manager"
  - "components/file_manager"
  - "components/svc_manager"
  - "proto"
  - "providers"
  - "sbe/bindings"
  - "sbe/schema"
  - "service_utils"
  - "services"
  - "tools"