############################
# This Dockerfile runs relative to the repo root.
# Therefore, copy it to the root folder before running.
############################
FROM asia-northeast1-docker.pkg.dev/future-309012/image-repo/rust-build:1.77-alpine as build

# Set workspace directory
WORKDIR /app

# Copy over the entire source code
COPY . ./

# Fetch dependencies if they change.
RUN set -x && cargo fetch

# Run the release build.
RUN cargo build -p binance_data --release --target aarch64-unknown-linux-musl

# Move binary up to root level directory for easy access
RUN mv /app/target/aarch64-unknown-linux-musl/release/binance_data /binance_data

# Strip the binary to reduce its size
RUN strip -s /binance_data

############################
# Scratch image
############################
FROM asia-northeast1-docker.pkg.dev/future-309012/image-repo/rust-scratch:1.77-alpine as runner

# Copy binary from build output directory
COPY --from=builder /binance_data /

# Port number must match deployment.yaml and specs/*/service_info
# service port: 4040
# metrics port: 8080
EXPOSE 4040 8080

# Run binary as unprivileged user
USER nobody:nobody

# Hard coded start command b/c no shell in scratch image
CMD ["/binance_data"]
