# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: v1
data:
  DNS_SERVER: MTAuOTYuMC4xMA==
kind: Secret
metadata:
  creationTimestamp: null
  name: dns-access
  namespace: default
type: Opaque