---
apiVersion: v1
kind: Service
metadata:
  name: dbgw-service
  namespace: default
spec:
  selector:
    app: dbgw
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: main-port
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: metrics-port
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbgw
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dbgw
  template:
    metadata:
      labels:
        app: dbgw
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: dbgw
          image: asia-northeast1-docker.pkg.dev/future-309012/image-repo/dbgw:38e3072f-20241014034731 # {"$imagepolicy": "default:dbgw-image-policy"}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 9090
            - containerPort: 8080
          env:
            - name: ENV
              value: "CLUSTER"
            - name: DNS_SERVER
              valueFrom:
                secretKeyRef:
                  name: dns-access
                  key: DNS_SERVER
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: database

          readinessProbe:
            grpc:
              port: 9090
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3

          livenessProbe:
            grpc:
              port: 9090
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3

          startupProbe:
            grpc:
              port: 9090
            initialDelaySeconds: 1
            failureThreshold: 5
            periodSeconds: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
