# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: service-migration-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: service-migration-image
  filterTags:
    # ${SHA:0:7}-$(date +%s) (numerical):
    pattern: '[a-fA-F0-9]+-(?P<timestamp>.*)'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc