# All configuration is documented online:
# https://cloudnative-pg.io/documentation/current/samples/
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgres

spec:
  description: "Postgres cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  imagePullPolicy: IfNotPresent
  primaryUpdateStrategy: unsupervised
  instances: 3
  bootstrap:
    initdb:
      database: quantum
      owner: dbgwuser
      secret:
        name: postgres-user

  storage:
    size: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-admin

  # enable monitoring with Prometheus
  monitoring:
    enablePodMonitor: true
---
