# All environment variables defined below are read in
# queng_components/config_manager/src/lib.rs
#
# PG app user is geneated in the setup staging cluster script to ensure it got a random password.
#
# The root / admin user below is only used for testing and staging and is not used in production.
---
apiVersion: v1
data:
  username: "cG9zdGdyZXM=" # printf postgres | base64
  password: "cG9zdGdyZXM=" # printf postgres | base64
kind: Secret
metadata:
  name: postgres-admin
  labels: # https://github.com/cloudnative-pg/cloudnative-pg/issues/2658
    cnpg.io/reload: ""
type: kubernetes.io/basic-auth
---
