use std::net::IpAddr;
use std::str::FromStr;

use futures::{future, prelude::*};
use tarpc::server;
use tarpc::server::incoming::Incoming;
use tarpc::server::Channel;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{print_utils, ServiceID};
use components::prelude::{CfgManager, CtxManager, DnsManager, EnvManager, ServiceManager};
use qdgw_service::service::{QDGateway, QDGatewayServer};
use smdb_provider::SMDBProvider;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let svc_id = ServiceID::QDGW;
    let ctx_manager = CtxManager::new();
    let dns_manager = DnsManager::new(&ctx_manager);
    let cfg_manager = CfgManager::new(svc_id, &ctx_manager);
    let svm_manager = EnvManager::new(&ctx_manager, &dns_manager);
    let service_manager = ServiceManager::new(&cfg_manager, &svm_manager);
    let smdb_provider = SMDBProvider::new(&service_manager).await;

    //get all dependencies
    let dependencies = service_manager.get_service_dependencies();

    // Check if there are any dependencies
    if !dependencies.is_empty() {
        // Check if all dependencies are online, abort of anyone is missing.
        for d in dependencies {
            let available = smdb_provider
                .check_if_service_id_exists(d)
                .await
                .expect("[QDGW]: Failed to check if service dependency exists");

            if !available {
                panic!(
                    "[QDGW]: Service dependency {:?} is not available please start it",
                    d
                );
            }
        }
    }

    // service_manager configures ip and port automatically relative to the detected context.
    let (host_ip, port) = service_manager
        .get_service_host_port(svc_id)
        .expect("[QDGW]: Failed to get CMDB host and port");
    let ip = IpAddr::from_str(&host_ip).expect("CMDB: Failed to parse host ip");
    let server_addr = (ip, port);

    // Dummy endpoint until service is migrated to new service model with metrics endpoint
    let metrics_port = 8080;
    let metrics_uri = "metrics".to_string();

    // Set CMDB service to online via SMDB
    smdb_provider
        .set_service_online(svc_id)
        .await
        .expect("[QDGW]: Failed to set CMDB service to online");

    print_utils::print_start_header(&svc_id, server_addr.1, &metrics_uri, metrics_port);

    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| {
            let server = QDGatewayServer::new();
            channel.execute(server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
