use crate::SymbolManager;
use common_errors::LookupError;

impl SymbolManager {
    /// Retrieves the database table name for the given exchange ID and symbol ID.
    ///
    /// # Arguments
    ///
    /// * `exchange_id` - The ID of the exchange to look up
    /// * `symbol_id` - The ID of the symbol to look up
    ///
    /// # Returns
    ///
    /// Returns a `String` containing the symbol table name in the format
    /// `{exchange_name}_{symbol}`, or a `LookupError` if the exchange or symbol
    /// could not be found.
    ///
    ///
    /// # Notes
    ///
    /// The symbol table name is generated by looking up the exchange name and symbol
    /// based on the provided IDs, and concatenating them with an underscore.
    pub fn get_symbol_table_name(
        &mut self,
        exchange_id: u16,
        symbol_id: u16,
    ) -> Result<String, LookupError> {
        let symbol = match self.get_symbol(symbol_id) {
            Ok(symbol) => symbol,
            Err(err) => return Err(err),
        };

        let exchange_name = match self.get_exchange_name(exchange_id) {
            Ok(exchange) => exchange,
            Err(err) => return Err(err),
        };

        let symbol_table_name = format!("{exchange_name}_{symbol}");

        Ok(symbol_table_name)
    }

    /// Retrieves the database table name for the symbols on the given exchange.
    ///
    /// # Arguments
    ///
    /// * `exchange_id` - The ID of the exchange
    ///
    /// # Returns
    ///
    /// Returns a `String` containing the symbol table name in the format
    /// `{exchange_name}_symbols`, or a `LookupError` if the exchange could not be found.
    ///
    pub fn get_symbol_table(&mut self, exchange_id: u16) -> Result<String, LookupError> {
        //
        let exchange_name = match self.get_exchange_name(exchange_id) {
            Ok(exchange) => exchange,
            Err(err) => return Err(err),
        };

        let symbol_table_name = format!("{exchange_name}_symbols");

        Ok(symbol_table_name)
    }
}
