# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pre-deploy-services-migration
  namespace: flux-system
spec:
  path: ".delivery/app/staging/pre-deploy/services-migration"
  targetNamespace: default
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pre-deploy-kaiko
  namespace: flux-system
spec:
  path: ".delivery/app/staging/pre-deploy/kaiko-proxy"
  targetNamespace: default
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pre-deploy-metadata-migration
  namespace: flux-system
spec:
  dependsOn:
    - name: pre-deploy-kaiko
  path: ".delivery/app/staging/pre-deploy/metadata-migration"
  targetNamespace: default
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---