# All environment variables defined below are read in
# queng_components/config_manager/src/lib.rs
---
apiVersion: v1
data:
  username: "USERNAME"
  password: "TOPSECRET"
kind: Secret
metadata:
  name: SECRETID
  labels:
    cnpg.io/reload: ""
type: kubernetes.io/basic-auth
---