---
apiVersion: v1
kind: Service
metadata:
  name: qdgw-service
  namespace: default

spec:
  selector:
    app: qdgw
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: main-port
      port: 4040
      protocol: TCP
      targetPort: 4040
    - name: metrics-port
      port: 8080
      protocol: TCP
      targetPort: 8080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdgw
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdgw
  template:
    metadata:
      labels:
        app: qdgw
    spec:
      containers:
        - name: qdgw
          image: gcr.io/future-309012/qdgw:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "CLUSTER"

            - name: DNS_SERVER
              valueFrom:
                secretKeyRef:
                  name: dns-access
                  key: DNS_SERVER

          ports:
            - containerPort: 4040
            - containerPort: 8080

# Define a gRPC liveness probe
#  https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe
          livenessProbe:
            grpc:
              port: 4040
            initialDelaySeconds: 3
            failureThreshold: 1
            periodSeconds: 3

          startupProbe:
            grpc:
              port: 4040
            initialDelaySeconds: 1
            failureThreshold: 10
            periodSeconds: 3

