# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/proxies/kaiko-proxy
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md
# https://fluxcd.io/flux/components/kustomize/kustomizations/#patches
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kaiko-proxy
        namespace: default
      spec:
        replicas: 0
---
