use std::net::{IpAddr, Ipv4Addr};

use service::PORT;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let _server_addr = (IpAddr::V4(Ipv4Addr::LOCALHOST), PORT);

    println!("Tarpc Example Client");
    // let mut transport = tarpc::serde_transport::tcp::connect(server_addr, Bincode::default);
    // transport.config_mut().max_frame_length(usize::MAX);

    // WorldClient is generated by the service attribute. It has a constructor `new` that takes a
    // config and any Transport as input.
    // let client = WorldClient::new(client::Config::default(), transport.await?).spawn();

    // Let the background span processor finish.
    // sleep(Duration::from_micros(10)).await;

    Ok(())
}
