use std::net::{IpAddr, Ipv4Addr};

use tarpc::{client, context, tokio_serde::formats::Bincode};

use service::{PORT, WorldClient};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let name = "John Doe";
    let server_addr = (IpAddr::V4(Ipv4Addr::LOCALHOST), PORT);

    println!("Tarpc Example Client");
    let mut transport = tarpc::serde_transport::tcp::connect(server_addr, Bincode::default);
    transport.config_mut().max_frame_length(usize::MAX);

    // WorldClient is generated by the service attribute. It has a constructor `new` that takes a
    // config and any Transport as input.
    let client = WorldClient::new(client::Config::default(), transport.await?).spawn();


    let hello = async move {
        tokio::select! {
            hello1 = client.hello(context::current(), format!("{}", name)) => { hello1 }
        }
    }.await;


    match hello {
        Ok(hello) => println!("{hello:?}"),
        Err(e) => println!("{:?}", anyhow::Error::from(e)),
    }

    // Let the background span processor finish.
    // sleep(Duration::from_micros(10)).await;

    Ok(())
}