use std::net::{IpAddr, Ipv4Addr};

use futures::{future, prelude::*};
use surrealdb::engine::local;
use surrealdb::Error;
use surrealdb::Surreal;
use tarpc::server;
use tarpc::server::Channel;
use tarpc::server::incoming::Incoming;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{print_utils, ServiceID};
use components::prelude::{DBManager, Status};
use service::{HelloServer, PORT};
use service::World;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Build a new db manager
    let dbm = get_dbm().await.unwrap();
    let status = dbm.status().await.unwrap();
    assert_eq!(status, Status::Connected);

    print_utils::print_start_header(&ServiceID::MEMGRAPH, PORT);

    let server_addr = (IpAddr::V4(Ipv4Addr::LOCALHOST), PORT);

    // JSON transport is provided by the json_transport tarpc module. It makes it easy
    // to start up a serde-powered json serialization strategy over TCP.
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| {
            let server = HelloServer::new(channel.transport().peer_addr().unwrap());
            channel.execute(server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    println!("Tarpc Example Server Stopped");

    Ok(())
}

async fn get_dbm() -> Result<DBManager, Error> {
    let db: Surreal<local::Db> = Surreal::new::<local::Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    let dbm = DBManager::new(db);

    Ok(dbm)
}
