use std::net::IpAddr;
use std::str::FromStr;

use futures::{future, prelude::*};
use tarpc::server;
use tarpc::server::incoming::Incoming;
use tarpc::server::Channel;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{print_utils, ServiceID};
use components::prelude::{CfgManager, CtxManager, DnsManager, ServiceManager, SvcEnvManager};
use service::service::{DBGateway, DBGatewayServer};

mod utils;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let svc_id = ServiceID::MEMGRAPH;
    let ctx_manager = CtxManager::new();
    let dns_manager = DnsManager::new(&ctx_manager);
    let cfg_manager = CfgManager::new(svc_id, &ctx_manager);
    let svm_manager = SvcEnvManager::new(&ctx_manager, &dns_manager);

    // service_manager configures ip and port fully automatically relative to the detected context.
    let service_manager = ServiceManager::new_offline_service_manager(&cfg_manager, &svm_manager);
    service_manager
        .init_service(&svc_id)
        .expect("Failed to init service autoconfig");
    let (host_ip, port) = service_manager
        .get_service_host_port(svc_id)
        .expect("Failed to get host and port");
    let ip = IpAddr::from_str(&host_ip).expect("Failed to parse host ip");
    let server_addr = (ip, port);

    // Build a new db manager
    let dbm = utils::get_dbm().await.unwrap();

    print_utils::print_start_header(&ServiceID::MEMGRAPH, port);

    // JSON transport is provided by the json_transport tarpc module. It makes it easy
    // to start up a serde-powered json serialization strategy over TCP.
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| {
            let server = DBGatewayServer::new(dbm.clone());
            channel.execute(server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
