# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-migration
  - services-migration
---
