apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgres

spec:
  description: "Postgres cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  imagePullPolicy: IfNotPresent
  primaryUpdateStrategy: unsupervised
  instances: 3
  bootstrap:
    initdb:
      database: quantum
      owner: dbgwuser
      secret:
        name: cluster-pg-user

  storage:
    size: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-pg-admin

  # enable monitoring with Prometheus
  monitoring:
    enablePodMonitor: true
---
# All environment variables defined below are read in
# queng_components/config_manager/src/lib.rs
---
apiVersion: v1
data:
  username: ZGJnd3VzZXI= # printf dbgwuser | base64
  password: WHZb0sFAU61W4xRyYE931oAEzc1MMgZy6gNUwyTwjJc= # openssl rand -base64 32
kind: Secret
metadata:
  name: cluster-pg-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  username: cG9zdGdyZXM= # printf postgres | base64
  password: cG9zdGdyZXM= # printf postgres | base64
kind: Secret
metadata:
  name: cluster-pg-admin
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  database: quantum
kind: Secret
metadata:
  name: cluster-pg-database
type: Opaque