---
apiVersion: v1
kind: Service
metadata:
  name: mddb-service
  namespace: default

spec:
  selector:
    app: mddb
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: main-port
      port: 7070
      protocol: TCP
      targetPort: 7070
    - name: metrics-port
      port: 8080
      protocol: TCP
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mddb
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mddb
  template:
    metadata:
      labels:
        app: mddb
    spec:
      containers:
        - name: mddb
          image: asia-northeast1-docker.pkg.dev/future-309012/image-repo/mddb:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "CLUSTER"

            - name: DNS_SERVER
              valueFrom:
                secretKeyRef:
                  name: dns-access
                  key: DNS_SERVER

          ports:
            - containerPort: 7070
            - containerPort: 8080

          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 3
            failureThreshold: 1
            periodSeconds: 3

          startupProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 1
            failureThreshold: 10
            periodSeconds: 3

