apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: smdb-image-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: smdb-image
    namespace: default
  filterTags:
    # ${SHA:0:7}-$(date +%s) (numerical):
    pattern: '[a-fA-F0-9]+-(?P<timestamp>.*)'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc