# Copyright (c) 2024. Marvin Friedrich Lars Hansen. All Rights Reserved. Contact: marvin.hansen@gmail.com
---
apiVersion: v1
kind: Service
metadata:
  name: smdb-service
  namespace: default
spec:
  selector:
    app: smdb
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: main-port
      port: 7070
      protocol: TCP
      targetPort: 7070
    - name: metrics-port
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smdb
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: smdb
  template:
    metadata:
      labels:
        app: smdb
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: smdb
          image: asia-northeast1-docker.pkg.dev/future-309012/image-repo/smdb:6a8ce0f9-20241014035955 # {"$imagepolicy": "default:smdb-image-policy"}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi

          ports:
            - containerPort: 7070
            - containerPort: 8080

          env:
            - name: ENV
              value: "CLUSTER"
            - name: DNS_SERVER
              valueFrom:
                secretKeyRef:
                  name: dns-access
                  key: DNS_SERVER

          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3

          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 1
            failureThreshold: 3
            periodSeconds: 3

          startupProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 1
            failureThreshold: 5
            periodSeconds: 3
