use std::net::IpAddr;
use std::str::FromStr;

use futures::{future, prelude::*};
use surrealdb::engine::local;
use surrealdb::{Error, Surreal};
use tarpc::server;
use tarpc::server::incoming::Incoming;
use tarpc::server::Channel;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{print_utils, ServiceID};
use components::prelude::{
    CfgManager, CtxManager, DBManager, DnsManager, ServiceManager, SvcEnvManager,
};
use dbgw_service::service::{DBGateway, DBGatewayServer};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let svc_id = ServiceID::DBGW;
    let ctx_manager = CtxManager::new();
    let dns_manager = DnsManager::new(&ctx_manager);
    let cfg_manager = CfgManager::new(svc_id, &ctx_manager);
    let svm_manager = SvcEnvManager::new(&ctx_manager, &dns_manager);
    let service_manager = ServiceManager::new_offline_service_manager(&cfg_manager, &svm_manager);

    // service_manager configures ip and port automatically relative to the detected context.
    let (host_ip, port) = service_manager
        .get_service_host_port(svc_id)
        .expect("DBGW: Failed to get host and port");

    let ip = IpAddr::from_str(&host_ip).expect("DBGW: Failed to parse host ip");

    let server_addr = (ip, port);

    // pull dbm config from autoconfig
    let dbm = get_dbm().await.unwrap();

    // TODO Set DBGW service to online
    //

    print_utils::print_start_header(&svc_id, server_addr.1);

    // JSON transport is provided by the json_transport tarpc module.
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| {
            let dbgw_server = DBGatewayServer::new(dbm.clone());
            channel.execute(dbgw_server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}

pub async fn get_dbm() -> Result<DBManager, Error> {
    let db: Surreal<local::Db> = Surreal::new::<local::Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    let dbm = DBManager::new(db);

    Ok(dbm)
}
