VERSION --global-cache 0.7
IMPORT github.com/earthly/lib/rust:2.2.11 AS rust

FROM hansenmarvin/rust-build:1.76-alpine

# Set workspace directory
WORKDIR /common

install:
  DO rust+INIT --keep_fingerprints=true

source:
  FROM +install
  COPY --keep-ts Cargo.toml ./
  COPY --keep-ts --dir src ./

build:
  FROM +source
  DO rust+CARGO --args="build --release" --output="release/[^/\.]+"
  SAVE ARTIFACT ./target/release/rust-common
