use std::net::IpAddr;
use std::str::FromStr;

use futures::{future, prelude::*};
use tarpc::server;
use tarpc::server::Channel;
use tarpc::server::incoming::Incoming;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{HostEndpoint, print_utils, ServiceID};
use common::prelude::ServiceID::DBGW;
use components::prelude::{CfgManager, CtxManager, DnsManager, EnvManager, ServiceManager};
use dbgw_client::DBGatewayClient;
use smdb_service::service::{SMDBServer, SMDBService};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let svc_id = ServiceID::SMDB;
    let ctx_manager = CtxManager::new();
    let dns_manager = DnsManager::new(&ctx_manager);
    let cfg_manager = CfgManager::new(svc_id, &ctx_manager);
    let svm_manager = EnvManager::new(&ctx_manager, &dns_manager);
    let service_manager = ServiceManager::new(&cfg_manager, &svm_manager);

    // pull DBGW endpoint from auto config
    let (dbgw_host, dbgw_port) = service_manager
        .get_service_host_port(DBGW)
        .expect("Failed to get host and port for DBGW");

    let dbgw_endpoint = HostEndpoint::new(&dbgw_host, dbgw_port);
    let dbgw_client = DBGatewayClient::new(dbgw_endpoint).await;

    // service_manager configures SMDB ip and port automatically relative to the detected context.
    let (host_ip, port) = service_manager
        .get_service_host_port(svc_id)
        .expect("SMDB: Failed to get host and port");

    let ip = IpAddr::from_str(&host_ip).expect("SMDB: Failed to parse host ip");
    let server_addr = (ip, port);

    // Dummy endpoint until service is migrated to new service model with metrics endpoint
    let metrics_uri = "metrics".to_string();
    let metrics_port = 8080;

    // Set SMDB service to online
    dbgw_client
        .set_service_online(ServiceID::SMDB)
        .await
        .expect("Failed to set service online");

    print_utils::print_start_header(&svc_id, server_addr.1, &metrics_uri, metrics_port);

    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| channel.execute(SMDBServer::new(dbgw_client.clone()).serve()))
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
