use std::net::IpAddr;
use std::str::FromStr;

use futures::{future, prelude::*};
use tarpc::server;
use tarpc::server::Channel;
use tarpc::server::incoming::Incoming;
use tarpc::tokio_serde::formats::Bincode;

use common::prelude::{HostEndpoint, print_utils, ServiceID};
use common::prelude::ServiceID::DBGW;
use components::prelude::{CfgManager, CtxManager, DnsManager, ServiceManager, SvcEnvManager};
use dbgw_client::DBGatewayClient;
use smdb_service::service::{SMDBServer, SMDBService};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let svc_id = ServiceID::SMDB;
    let ctx_manager = CtxManager::new();
    let dns_manager = DnsManager::new(&ctx_manager);
    let cfg_manager = CfgManager::new(svc_id, &ctx_manager);
    let svm_manager = SvcEnvManager::new(&ctx_manager, &dns_manager);
    let service_manager = ServiceManager::new_offline_service_manager(&cfg_manager, &svm_manager);
    // service_manager configures ip and port automatically relative to the detected context.
    let (host_ip, port) = service_manager
        .get_service_host_port(svc_id)
        .expect("Failed to get host and port");
    let ip = IpAddr::from_str(&host_ip).expect("Failed to parse host ip");
    let server_addr = (ip, port);

    // pull DBGW endpoint from auto config
    let (dbgw_host, dbgw_port) = service_manager
        .get_service_host_port(DBGW)
        .expect("Failed to get host and port");

    let dbgw_endpoint = HostEndpoint::new(&dbgw_host, dbgw_port);
    let dbgw_lient = DBGatewayClient::new(dbgw_endpoint).await;

    print_utils::print_start_header(&svc_id, server_addr.1);

    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Bincode::default).await?;
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute.
        .map(|channel| {
            let server = SMDBServer::new(dbgw_lient.clone());
            channel.execute(server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
