#SPDX-License-Identifier: MIT
#Copyright (c) "2023" . The DeepCausality Authors. All Rights Reserved.

name: Tests
on: [ pull_request, push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test Environment
        run: echo "ENVIRONMENT IS  ${{ env.ENV }} DNS SERVER IS ${{ env.DNS_SERVER }}"

      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
        env:
          ENV: ${{ env.ENV }}
          DNS_SERVER: ${{ env.DNS_SERVER }}

      - name: Run tests
        run: cargo test --verbose
        env:
          ENV: ${{ env.ENV }}
          DNS_SERVER: ${{ env.DNS_SERVER }}