#SPDX-License-Identifier: MIT
#Copyright (c) "2023" . The DeepCausality Authors. All Rights Reserved.

name: Tests
on: [ pull_request, push ]

env:
  CARGO_TERM_COLOR: always
  ENV: CLUSTER
  DNS_SERVER: 9.9.9.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment
        run: echo "ENVIRONMENT IS ${{env.ENV}} DNS SERVER IS ${{env.DNS_SERVER}}"

      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
