apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "pv-log"
spec:
  configuration:
    users:
      user2/networks/ip: "::/0"
      user2/password: qwerty
      user2/profile: default
      # readonly user
      readonly/password: readonly_password
      readonly/profile: readonly
      readonly/quota: default
    clusters:
      - name: "deployment-pv"
        # Templates are specified for this cluster explicitly
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: 2
          replicasCount: 2

  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              # https://hub.docker.com/r/clickhouse/clickhouse-server/tags
              image: clickhouse/clickhouse-server:24.3.1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 1000m
                  memory: 1024i
                  nvidia.com/gpu: '0'
                limits:
                  cpu: 2500m
                  memory: 2048Mi
                  nvidia.com/gpu: '0'
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server

    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
